const translations = {
    sv: {
        title: "Matlådebyggare 6.0",
        tab_build: "Byggaren",
        tab_batch: "Storkok",
        tab_freezer: "Frys",
        tab_pantry: "Skafferi",
        tab_schedule: "Matsedel",
        tab_settings: "Inställningar",
        lbl_layout: "Form- & batch-storlek:",
        layout_4: "4 st lådor (max 250 ml)",
        layout_2: "2 st stora lådor (max 500 ml)",
        layout_6: "6 st små lådor (max 125 ml)",
        layout_10: "10 st såskuber (max 30 ml)",
        lbl_mode: "Recepttyp per låda:",
        mode_2: "2 Ingredienser (Protein + Bas)",
        mode_1: "1 Ingrediens (Enkelråvara / Soppa)",
        btn_save: "Spara",
        btn_reset: "Återställ",
        btn_freeze: "Skicka till Frys",
        btn_copy: "Kopiera inköpslista",
        tip_intro: "Justera volymreglagen för att direkt se kostnad, näringsvärde och exakt inköpsmängd.",
        shopping_title: "Inköpslista",
        p_header: "Protein & Chark",
        c_header: "Kolhydrater & Bas",
        total_price: "Beräknad totalursprungskostnad:",
        kitchen_title: "Köksinstruktioner",
        compartment: "Fack / Låda ",
        vol_label: "Volym:",
        prot_label: "Protein-råvara:",
        carb_label: "Kolhydrat-råvara:",
        prot_pct: "Proteinandel:",
        style_layered: "Lager-på-lager",
        style_allinone: "Allt-i-ett (Mixad)",
        btn_print: "Skriv ut etikett",
        
        // Komponenter
        tab_components: "Komponenter",
        comp_title: "🧩 Skapa Skräddarsydd Protein- eller Bas-komponent",
        comp_sub: "Bygg egna sammansatta komponenter som sedan dyker upp direkt i Byggarens rullgardiner!",
        comp_load_lbl: "Ladda sparad komponent:",
        comp_type_lbl: "Typ av komponent",
        comp_type_p: "Protein-komponent",
        comp_type_c: "Bas-komponent (Kolhydrat)",
        comp_name_lbl: "Komponentens namn",
        comp_name_ph: "T.ex. Vitlökspotatismos",
        comp_ing_header: "Ingredienser som ingår (totalmängd för hela satsen):",
        comp_macro_header: "Beräknat näringsvärde per 100g färdig komponent:",
        btn_save_comp: "💾 Spara komponent till Byggaren",

        lbl_template: "Ladda sparad mall:",
        btn_load: "Ladda",
        btn_delete: "Radera",
        lbl_recipe_name: "Receptets namn",
        lbl_yield: "Antal färdiga portioner/lådor",
        lbl_batch_ing: "Ingredienser för hela satsen:",
        btn_add: "Lägg till",
        lbl_batch_calc: "Beräknat per färdig portion/låda:",
        btn_send_batch: "Skicka storkok till frysen",
        btn_save_template: "Spara mall",
        lbl_freezer_header: "Mitt Permanenta Fryslager",
        lbl_freezer_sub: "Visar infrysningsdatum, storlek (ml) och utgångsdatum (3 månaders hållbarhet).",
        lbl_freezer_empty: "Frysen är tom.",
        lbl_pantry_header: "Mitt Skafferilager",
        lbl_pantry_sub: "Här ser du vad som finns kvar i skafferiet efter kub-beräkningen.",
        lbl_pantry_empty: "Skafferiet är tomt.",
        btn_used_other: "Använt till annat",
        lbl_schedule_header: "Veckomatsedel & Tallriksvy",
        lbl_schedule_sub: "Bygg ihop din tallrik med flera komponenter direkt från frysen.",
        btn_add_box: "+ Lägg till låda",
        btn_eat_plate: "🍽️ Ät upp tallriken (Dra av från frys)",
        lbl_lang_header: "Språk / Language",
        lbl_lang_sub: "Välj språk för hela applikationen:",
        lbl_add_ing_header: "Lägg till ny råvara",
        btn_add_system: "Lägg till i systemet",
        lbl_edit_header: "Redigera Priser & Butiksvaror",
        th_name: "Namn (Butik)",
        th_size: "Storlek",
        th_price: "Pris (kr)",
        th_action: "Åtgärd",
        btn_save_edits: "Spara alla ändringar"
    },
    en: {
        title: "Meal Prep Builder 6.0",
        tab_build: "Builder",
        tab_batch: "Batch Cooking",
        tab_freezer: "Freezer",
        tab_pantry: "Pantry",
        tab_schedule: "Schedule",
        tab_settings: "Settings",
        lbl_layout: "Container & Batch Size:",
        layout_4: "4 boxes (max 250 ml)",
        layout_2: "2 large boxes (max 500 ml)",
        layout_6: "6 small boxes (max 125 ml)",
        layout_10: "10 sauce cubes (max 30 ml)",
        lbl_mode: "Recipe Type per Box:",
        mode_2: "2 Ingredients (Protein + Base)",
        mode_1: "1 Ingredient (Single / Soup)",
        btn_save: "Save",
        btn_reset: "Reset",
        btn_freeze: "Send to Freezer",
        btn_copy: "Copy Shopping List",
        tip_intro: "Adjust volume sliders to instantly see cost, macros, and exact shopping amounts.",
        shopping_title: "Shopping List",
        p_header: "Protein & Meat",
        c_header: "Carbs & Base",
        total_price: "Estimated total cost:",
        kitchen_title: "Kitchen Instructions",
        compartment: "Compartment / Box ",
        vol_label: "Volume:",
        prot_label: "Protein Source:",
        carb_label: "Carb Source:",
        prot_pct: "Protein Share:",
        style_layered: "Layered",
        style_allinone: "All-in-one (Mixed)",
        btn_print: "Print Label",

        // Components
        tab_components: "Components",
        comp_title: "🧩 Create Custom Protein or Base Component",
        comp_sub: "Build your own composite components that will appear directly in the Builder dropdowns!",
        comp_load_lbl: "Load saved component:",
        comp_type_lbl: "Component Type",
        comp_type_p: "Protein Component",
        comp_type_c: "Base Component (Carb)",
        comp_name_lbl: "Component Name",
        comp_name_ph: "E.g. Garlic Mashed Potatoes",
        comp_ing_header: "Included ingredients (total amount for full batch):",
        comp_macro_header: "Estimated nutritional value per 100g finished component:",
        btn_save_comp: "💾 Save Component to Builder",

        lbl_template: "Load Saved Template:",
        btn_load: "Load",
        btn_delete: "Delete",
        lbl_recipe_name: "Recipe Name",
        lbl_yield: "Yield (Portions/Boxes)",
        lbl_batch_ing: "Ingredients for full batch:",
        btn_add: "Add",
        lbl_batch_calc: "Estimated per finished portion/box:",
        btn_send_batch: "Send batch to freezer",
        btn_save_template: "Save Template",
        lbl_freezer_header: "My Permanent Freezer Stock",
        lbl_freezer_sub: "Shows freezing date, size (ml), and expiration date (3 months shelf life).",
        lbl_freezer_empty: "The freezer is empty.",
        lbl_pantry_header: "My Pantry Stock",
        lbl_pantry_sub: "Shows leftover ingredients in your pantry after calculations.",
        lbl_pantry_empty: "The pantry is empty.",
        btn_used_other: "Used elsewhere",
        lbl_schedule_header: "Weekly Schedule & Plate View",
        lbl_schedule_sub: "Build your plate using multiple components straight from the freezer.",
        btn_add_box: "+ Add Box",
        btn_eat_plate: "🍽️ Eat Plate (Deduct from Freezer)",
        lbl_lang_header: "Language",
        lbl_lang_sub: "Choose application language:",
        lbl_add_ing_header: "Add New Ingredient",
        btn_add_system: "Add to System",
        lbl_edit_header: "Edit Prices & Store Items",
        th_name: "Name (Store)",
        th_size: "Size",
        th_price: "Price (SEK)",
        th_action: "Action",
        btn_save_edits: "Save All Changes"
    }
};

let currentLang = localStorage.getItem('matladeLang60') || 'sv';

function t(key) {
    return translations[currentLang][key] || key;
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('matladeLang60', lang);
    updateStaticTexts();
    initBuilder();
    calc();
}